{% set version = "0.5.3" %}

package:
  name: ipfsspec
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipfsspec/ipfsspec-{{ version }}.tar.gz
  sha256: d90999b149c9e476e0459d92a70162e563583cda24b3359da036624326d36da4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - aiohttp
    - fsspec >=0.9.0
    - requests

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - ipfsspec

about:
  home: https://github.com/fsspec/ipfsspec
  license: MIT
  license_file: LICENSE
  summary: A readonly implementation of fsspec for IPFS

extra:
  recipe-maintainers:
    - raybellwaves
